In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/raw_kolkata.csv", parse_dates=['date'])
df

                           date  temperature   humidity    pressure
0     2016-01-01 18:30:00+00:00    16.111000  90.241035  1018.47614
1     2016-01-01 19:30:00+00:00    15.461000  91.371770  1017.87415
2     2016-01-01 20:30:00+00:00    14.961000  92.234870  1017.47210
3     2016-01-01 21:30:00+00:00    14.511001  92.811740  1017.37030
4     2016-01-01 22:30:00+00:00    14.461000  92.507000  1016.67084
...                         ...          ...        ...         ...
70099 2023-12-31 13:30:00+00:00    17.900000  83.689150  1014.38940
70100 2023-12-31 14:30:00+00:00    17.850000  82.082560  1014.78890
70101 2023-12-31 15:30:00+00:00    17.550000  81.780350  1014.98740
70102 2023-12-31 16:30:00+00:00    16.350000  87.107796  1014.98160
70103 2023-12-31 17:30:00+00:00    15.500000  91.078690  1014.57840

[70104 rows x 4 columns]

In [3]:
df['label'] = 'normal'
df

                           date  temperature   humidity    pressure   label
0     2016-01-01 18:30:00+00:00    16.111000  90.241035  1018.47614  normal
1     2016-01-01 19:30:00+00:00    15.461000  91.371770  1017.87415  normal
2     2016-01-01 20:30:00+00:00    14.961000  92.234870  1017.47210  normal
3     2016-01-01 21:30:00+00:00    14.511001  92.811740  1017.37030  normal
4     2016-01-01 22:30:00+00:00    14.461000  92.507000  1016.67084  normal
...                         ...          ...        ...         ...     ...
70099 2023-12-31 13:30:00+00:00    17.900000  83.689150  1014.38940  normal
70100 2023-12-31 14:30:00+00:00    17.850000  82.082560  1014.78890  normal
70101 2023-12-31 15:30:00+00:00    17.550000  81.780350  1014.98740  normal
70102 2023-12-31 16:30:00+00:00    16.350000  87.107796  1014.98160  normal
70103 2023-12-31 17:30:00+00:00    15.500000  91.078690  1014.57840  normal

[70104 rows x 5 columns]

In [4]:
df.loc[1, 'temperature']

np.float64(15.461)

In [5]:
from weather_anamoly.utils import AnomalyInjection

In [47]:
anomaly_injector = AnomalyInjection()
df_anomaly = anomaly_injector.inject_anomalies(df=df.copy(), spike_rate=20, frozen_rate=50, comm_rate=150, drift_rate=6000)

In [48]:
df_anomaly.label.unique()

<StringArray>
['normal', 'spike', 'comm_error', 'frozen', 'fault']
Length: 5, dtype: str

In [49]:
print(df_anomaly['label'].eq('normal').sum())
print(df_anomaly['label'].eq('frozen').sum())
print(df_anomaly['label'].eq('comm_error').sum())
print(df_anomaly['label'].eq('spike').sum())
print(df_anomaly['label'].eq('fault').sum())

47031
8049
1159
2451
11414

In [50]:
df_anomaly.to_csv("data/anomaly_labelled_data.csv")