In [1]:
from weather_anamoly.utils import ImportData, ImportCoordinates

In [2]:
coordinates = ImportCoordinates()
data = ImportData()

In [17]:
st = "2016-01-02"
end = "2023-12-31"

In [18]:
latitude, longitude = coordinates.Fetch_coordinates("Kolkata")
df = data.extract(st, end, latitude, longitude)

In [19]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 70104 entries, 2016-01-01 18:30:00+00:00 to 2023-12-31 17:30:00+00:00
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   temperature  70104 non-null  float32
 1   humidity     70104 non-null  float32
 2   pressure     70104 non-null  float32
dtypes: float32(3)
memory usage: 1.3 MB

In [20]:
df.describe()

        temperature      humidity      pressure
count  70104.000000  70104.000000  70104.000000
mean      26.075901     77.294556   1006.537964
std        5.027254     16.826185      6.039414
min        8.750000     11.436662    961.587524
25%       23.450001     67.935658   1001.763550
50%       26.950001     82.081436   1006.625732
75%       29.250000     90.646784   1011.616241
max       42.150002    100.000000   1021.179077

In [21]:
df.tail()

                           temperature   humidity     pressure
date
2023-12-31 13:30:00+00:00    17.900000  83.689148  1014.389404
2023-12-31 14:30:00+00:00    17.850000  82.082558  1014.788879
2023-12-31 15:30:00+00:00    17.549999  81.780350  1014.987427
2023-12-31 16:30:00+00:00    16.350000  87.107796  1014.981628
2023-12-31 17:30:00+00:00    15.500000  91.078690  1014.578430

In [22]:
df.head()

                           temperature   humidity     pressure
date
2016-01-01 18:30:00+00:00    16.111000  90.241035  1018.476135
2016-01-01 19:30:00+00:00    15.461000  91.371773  1017.874146
2016-01-01 20:30:00+00:00    14.961000  92.234871  1017.472107
2016-01-01 21:30:00+00:00    14.511001  92.811737  1017.370300
2016-01-01 22:30:00+00:00    14.461000  92.507004  1016.670837

In [28]:
difference = df.diff().drop(index="2016-01-01 18:30:00+00:00")
difference

                           temperature  humidity  pressure
date
2016-01-01 19:30:00+00:00    -0.650000  1.130737 -0.601990
2016-01-01 20:30:00+00:00    -0.500000  0.863098 -0.402039
2016-01-01 21:30:00+00:00    -0.450000  0.576866 -0.101807
2016-01-01 22:30:00+00:00    -0.050000 -0.304733 -0.699463
2016-01-01 23:30:00+00:00     0.650000 -1.749573  0.702271
...                                ...       ...       ...
2023-12-31 13:30:00+00:00    -0.750000  3.073067  0.595764
2023-12-31 14:30:00+00:00    -0.049999 -1.606590  0.399475
2023-12-31 15:30:00+00:00    -0.300001 -0.302208  0.198547
2023-12-31 16:30:00+00:00    -1.199999  5.327446 -0.005798
2023-12-31 17:30:00+00:00    -0.850000  3.970894 -0.403198

[70103 rows x 3 columns]

In [34]:
import pandas as pd
import numpy as np

In [36]:
df = pd.read_csv("data/gradient_data_kolkata.csv", parse_dates=['date']).set_index('date')
df

                           temperature  humidity  pressure
date
2016-01-01 19:30:00+00:00    -0.650000  1.130737 -0.601990
2016-01-01 20:30:00+00:00    -0.500000  0.863098 -0.402039
2016-01-01 21:30:00+00:00    -0.450000  0.576866 -0.101807
2016-01-01 22:30:00+00:00    -0.050000 -0.304733 -0.699463
2016-01-01 23:30:00+00:00     0.650000 -1.749573  0.702271
...                                ...       ...       ...
2023-12-31 13:30:00+00:00    -0.750000  3.073067  0.595764
2023-12-31 14:30:00+00:00    -0.049999 -1.606590  0.399475
2023-12-31 15:30:00+00:00    -0.300001 -0.302208  0.198547
2023-12-31 16:30:00+00:00    -1.199999  5.327446 -0.005798
2023-12-31 17:30:00+00:00    -0.850000  3.970894 -0.403198

[70103 rows x 3 columns]

In [ ]:
df['hour'] = df.index.hour
df['month'] = df.index.month
df

                           temperature  humidity  pressure  hour  month
date
2016-01-01 19:30:00+00:00    -0.650000  1.130737 -0.601990    19      1
2016-01-01 20:30:00+00:00    -0.500000  0.863098 -0.402039    20      1
2016-01-01 21:30:00+00:00    -0.450000  0.576866 -0.101807    21      1
2016-01-01 22:30:00+00:00    -0.050000 -0.304733 -0.699463    22      1
2016-01-01 23:30:00+00:00     0.650000 -1.749573  0.702271    23      1
...                                ...       ...       ...   ...    ...
2023-12-31 13:30:00+00:00    -0.750000  3.073067  0.595764    13     12
2023-12-31 14:30:00+00:00    -0.049999 -1.606590  0.399475    14     12
2023-12-31 15:30:00+00:00    -0.300001 -0.302208  0.198547    15     12
2023-12-31 16:30:00+00:00    -1.199999  5.327446 -0.005798    16     12
2023-12-31 17:30:00+00:00    -0.850000  3.970894 -0.403198    17     12

[70103 rows x 5 columns]

converting raw hour and month numbers into some continuous cycle to have it continuous because as the 0hrs is exactly 1 hour from 23 hrs we could tell that by adding the cos and sine functions

In [44]:
df['cos_hour'] = np.cos(2*(np.pi)*df['hour']/24)
df['sin_hour'] = np.sin(2*np.pi*df['hour']/24)
df['cos_month'] = np.cos(2*np.pi*df['month']/12)
df['sin_month'] = np.sin(2*np.pi*df['month']/12)
df

,temperature,humidity,pressure,hour,month,cos_hour,sin_hour,cos_month,sin_month
date,,,,,,,,,
2016-01-01 19:30:00+00:00,-0.650000,1.130737,-0.601990,19,1,0.258819,-0.965926,0.866025,5.000000e-01
2016-01-01 20:30:00+00:00,-0.500000,0.863098,-0.402039,20,1,0.500000,-0.866025,0.866025,5.000000e-01
2016-01-01 21:30:00+00:00,-0.450000,0.576866,-0.101807,21,1,0.707107,-0.707107,0.866025,5.000000e-01
2016-01-01 22:30:00+00:00,-0.050000,-0.304733,-0.699463,22,1,0.866025,-0.500000,0.866025,5.000000e-01
2016-01-01 23:30:00+00:00,0.650000,-1.749573,0.702271,23,1,0.965926,-0.258819,0.866025,5.000000e-01
...,...,...,...,...,...,...,...,...,...
2023-12-31 13:30:00+00:00,-0.750000,3.073067,0.595764,13,12,-0.965926,-0.258819,1.000000,-2.449294e-16
2023-12-31 14:30:00+00:00,-0.049999,-1.606590,0.399475,14,12,-0.866025,-0.500000,1.000000,-2.449294e-16
2023-12-31 15:30:00+00:00,-0.300001,-0.302208,0.198547,15,12,-0.707107,-0.707107,1.000000,-2.449294e-16
2023-12-31 16:30:00+00:00,-1.199999,5.327446,-0.005798,16,12,-0.500000,-0.866025,1.000000,-2.449294e-16
2023-12-31 17:30:00+00:00,-0.850000,3.970894,-0.403198,17,12,-0.258819,-0.965926,1.000000,-2.449294e-16

Before standardisation as we can notice the temperature and humidity and pressure columns have medium, large, and low gradient values which will eventually make the model to consider the effect of humidity more on anomaly and less of pressure so we need to convert the columns into some standard scaled values since this is a timeseries and if we use StandardScaler from sklearn we would get one mean for the overall 8 years of data not for every month for every hour. so we need to standardise the data with considering the hour mean and standard deviation for every month.

In [45]:
df.to_csv("data/gradient_data_kolkata.csv")